### ISSUE TITLE
Link to Original Mish Repository

### ISSUE THREAD

**Issue by digantamisra98** [lessw2020/Ranger-Mish-ImageWoof-5#2]
Not an issue, but would be nice if you could add the links to the original repository of Mish - https://github.com/digantamisra98/Mish and to the paper here - https://arxiv.org/abs/1908.08681. It would be beneficial for readers as I keep updating the repository with added benchmarks and improved analysis. Thank you and congratulations!

**Comment by lessw2020** [comment]
All fixed!  Thanks for the links as until today I didn't even realize there was a github for it!
