### ISSUE TITLE
How did you choose learning rate?

### ISSUE THREAD

**Issue by hadaev8** [lessw2020/Ranger-Mish-ImageWoof-5#4]
Is it a higher value on lr finder curve?

**Comment by lessw2020** [comment]
Hi @hadaev8,
We did not use the lr finder from FastAI.  B/c that is for fit one cycle vs we are using flat + cosine anneal, the rates proposed from there are usually too high.
Thus, I simply tested some short 3-4 epoch runs using a flat lr, and adjusting the lr by 10x to create a quick spread of rates, and then honed in with that.
Hope that helps!
Less

**Comment by hadaev8** [comment]
Thanks
